"""Strategy builder service for v3 modular microservice architecture."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.strategies.strategy_builder import IndicatorType, LogicGate, StrategyBuilder

from .config import StrategyBuilderConfig
from .models import StrategyArtifact


class StrategyBuilderService:
    """Rule-based plus AI-assisted strategy composition service."""

    def __init__(self, config: Optional[StrategyBuilderConfig] = None):
        self.config = config or StrategyBuilderConfig()
        self.builder = StrategyBuilder()
        self._artifacts: Dict[str, StrategyArtifact] = {}

    def list_presets(self) -> List[str]:
        return list(self.builder.PRESETS.keys())

    def create_from_preset(self, preset_name: str, symbol: str = "BTC/USDT", timeframe: str = "5m") -> StrategyArtifact:
        strategy_id = self.builder.load_preset(preset_name, symbol=symbol, timeframe=timeframe)
        strategy = self.builder.get_strategy(strategy_id)

        artifact = StrategyArtifact(
            strategy_id=strategy_id,
            name=strategy.name,
            rules={
                "entry_long": strategy.entry_long.to_dict() if strategy.entry_long else {},
                "entry_short": strategy.entry_short.to_dict() if strategy.entry_short else {},
                "exit": strategy.exit_config.to_dict(),
                "filters": strategy.filter_config.to_dict(),
            },
            indicators=[condition.indicator.value for condition in (strategy.entry_long.conditions if strategy.entry_long else [])],
            smc_conditions=[
                condition.indicator.value
                for condition in (strategy.entry_long.conditions if strategy.entry_long else [])
                if condition.indicator.value in {"order_block", "fvg", "bos", "choch", "liquidity"}
            ],
            risk_rules=strategy.risk_config.to_dict(),
            metadata={
                "mode": self.config.strategy_type,
                "preset": preset_name,
                "drag_and_drop_logic": "enabled",
                "condition_chaining": "enabled",
                "multi_timeframe_rules": "enabled",
            },
        )
        self._artifacts[strategy_id] = artifact
        return artifact

    def create_custom_strategy(
        self,
        name: str,
        indicators: List[Any],
        smc_conditions: List[Any],
        risk_rules: Dict[str, Any],
        symbol: str = "BTC/USDT",
        timeframe: str = "5m",
        chain_operator: str = "AND",
        multi_timeframe_rules: Optional[Dict[str, Any]] = None,
    ) -> StrategyArtifact:
        strategy_id = self.builder.new_strategy(
            name=name,
            symbol=symbol,
            timeframe=timeframe,
            description="Custom strategy generated by v3 strategy builder",
        )

        gate_value = chain_operator.upper()
        strategy = self.builder.get_strategy(strategy_id)
        if strategy.entry_long:
            strategy.entry_long.gate = LogicGate(gate_value)
        if strategy.entry_short:
            strategy.entry_short.gate = LogicGate(gate_value)

        valid_indicators = {item.value for item in IndicatorType}
        all_blocks = list(indicators) + list(smc_conditions)
        normalized_conditions: List[Dict[str, Any]] = []

        for block in all_blocks:
            condition = self._normalize_block(block)
            if condition["indicator"] not in valid_indicators:
                continue

            self.builder.add_entry_condition(
                strategy_id,
                "long",
                indicator=condition["indicator"],
                params=condition["params"],
                operator=condition["operator"],
                threshold=condition["threshold"],
                description=condition["description"],
            )
            normalized_conditions.append(condition)

        if risk_rules:
            self.builder.set_risk_config(strategy_id, **risk_rules)

        strategy = self.builder.get_strategy(strategy_id)
        artifact = StrategyArtifact(
            strategy_id=strategy_id,
            name=strategy.name,
            rules={
                "entry_long": strategy.entry_long.to_dict() if strategy.entry_long else {},
                "entry_short": strategy.entry_short.to_dict() if strategy.entry_short else {},
                "exit": strategy.exit_config.to_dict(),
                "filters": strategy.filter_config.to_dict(),
                "multi_timeframe_rules": multi_timeframe_rules or {},
            },
            indicators=[item["indicator"] for item in normalized_conditions],
            smc_conditions=[
                item["indicator"]
                for item in normalized_conditions
                if item["indicator"] in {"order_block", "fvg", "bos", "choch", "liquidity"}
            ],
            risk_rules=strategy.risk_config.to_dict(),
            metadata={
                "mode": self.config.strategy_type,
                "drag_and_drop_logic": "enabled",
                "condition_chaining": gate_value,
                "multi_timeframe_rules": multi_timeframe_rules or {},
            },
        )
        self._artifacts[strategy_id] = artifact
        return artifact

    def ai_assisted_suggestions(self, market_profile: Dict[str, Any]) -> Dict[str, Any]:
        volatility = float(market_profile.get("volatility", 0.0))
        trend = str(market_profile.get("trend", "sideways"))

        suggestions = {
            "indicators": ["ema", "rsi"],
            "smc_conditions": ["order_block", "fvg"],
            "risk_rules": {"max_risk_pct": 0.01},
        }

        if trend == "bullish":
            suggestions["indicators"].append("vwap")
            suggestions["smc_conditions"].append("bos")
        elif trend == "bearish":
            suggestions["indicators"].append("supertrend")
            suggestions["smc_conditions"].append("choch")

        if volatility > 0.02:
            suggestions["risk_rules"]["max_risk_pct"] = 0.006
            suggestions["indicators"].append("atr")

        return suggestions

    def export_strategy(self, strategy_id: str, output_path: Optional[str] = None) -> str:
        payload = self.builder.export_json(strategy_id)
        export_target = Path(output_path or self.config.output)
        export_target.parent.mkdir(parents=True, exist_ok=True)
        export_target.write_text(payload, encoding="utf-8")
        return str(export_target)

    def save_artifact(self, artifact: StrategyArtifact, output_path: Optional[str] = None) -> str:
        target = Path(output_path or self.config.output)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(artifact.__dict__, default=str, indent=2), encoding="utf-8")
        return str(target)

    def get_artifact(self, strategy_id: str) -> Optional[StrategyArtifact]:
        return self._artifacts.get(strategy_id)

    @staticmethod
    def _normalize_block(block: Any) -> Dict[str, Any]:
        if isinstance(block, str):
            return {
                "indicator": block,
                "params": {},
                "operator": "==",
                "threshold": True,
                "description": f"Auto condition for {block}",
            }

        if isinstance(block, dict):
            return {
                "indicator": str(block.get("indicator", "")),
                "params": block.get("params", {}),
                "operator": str(block.get("operator", "==")),
                "threshold": block.get("threshold", True),
                "description": str(block.get("description", "")),
            }

        raise ValueError("Unsupported condition block format")
