"""
Data Authenticity Layer - v10.4-TRUST-GRADE

Prevents fake, stale, or placeholder data from appearing as live.
Ensures every data point rendered to the operator is trustworthy.

Features:
- Source tagging (LIVE, SIMULATED, STALE)
- Timestamp validation
- Staleness threshold alerts
"""

import logging
import time
from datetime import datetime, timedelta
from enum import Enum
from dataclasses import dataclass, field
from typing import Any, Dict, Optional, Generic, TypeVar

logger = logging.getLogger(__name__)

T = TypeVar('T')

class DataSource(Enum):
    """Origin of data."""
    LIVE = "live"             # Real-time from exchange API
    SIMULATED = "simulated"   # Generated by simulator/backtest
    STALE = "stale"           # Was live, but now too old
    CACHED = "cached"         # From local cache/database (check timestamp)
    PLACEHOLDER = "placeholder" # Should never appear in production


class AuthenticityStatus(Enum):
    """Status of data verification."""
    VERIFIED = "verified"     # Fresh and authentic
    WARNING = "warning"       # Authentic but potentially stale
    REJECTED = "rejected"     # Invalid source or too old


@dataclass
class AuthenticData(Generic[T]):
    """
    Wrapper for any critical data object (price, balance, position).
    Enforces metadata about origin and freshness.
    """
    data: T
    source: DataSource
    timestamp: datetime
    producer_id: str          # Who created this data (e.g., 'binance_client', 'simulator')
    environment: str          # 'live' or 'testnet' tag from EnvironmentGuard
    
    metadata: Dict = field(default_factory=dict)
    
    def is_stale(self, threshold_seconds: float) -> bool:
        """Check if data is older than threshold."""
        age = (datetime.utcnow() - self.timestamp).total_seconds()
        return age > threshold_seconds
    
    def to_dict(self) -> Dict:
        """Serialize for API/WebSocket."""
        return {
            'data': self.data,
            'source': self.source.value,
            'timestamp': self.timestamp.isoformat(),
            'producer_id': self.producer_id,
            'environment': self.environment,
            'age_seconds': (datetime.utcnow() - self.timestamp).total_seconds()
        }


class DataAuthenticityGuard:
    """
    Guard that validates incoming data before it reaches decision engine or UI.
    """
    
    STALENESS_THRESHOLDS = {
        'price': 5.0,        # 5 seconds for price
        'orderbook': 2.0,    # 2 seconds for book
        'balance': 60.0,     # 1 minute for balance
        'position': 10.0,    # 10 seconds for position updates
    }
    
    def __init__(self, environment_guard):
        self._env_guard = environment_guard
    
    def verify(self, data_wrapper: AuthenticData, data_type: str) -> AuthenticityStatus:
        """
        Verify data authenticity.
        """
        # 1. Environment Check
        current_env = self._env_guard.get_signature().mode.value
        if data_wrapper.environment != current_env:
            logger.error(f"DATA REJECTED: Environment mismatch! Data env={data_wrapper.environment}, System env={current_env}")
            return AuthenticityStatus.REJECTED
            
        # 2. Source Check
        if data_wrapper.source == DataSource.PLACEHOLDER:
            if current_env == "live":
                logger.critical("DATA REJECTED: Placeholder data in LIVE environment")
                return AuthenticityStatus.REJECTED
                
        # 3. Staleness Check
        threshold = self.STALENESS_THRESHOLDS.get(data_type, 30.0)
        if data_wrapper.is_stale(threshold):
            logger.warning(f"DATA WARNING: Stale {data_type} received. Age: {(datetime.utcnow() - data_wrapper.timestamp).total_seconds():.2f}s")
            return AuthenticityStatus.WARNING
            
        return AuthenticityStatus.VERIFIED

    def wrap(self, data: T, source: DataSource, producer: str) -> AuthenticData[T]:
        """
        Create an AuthenticData wrapper with current environment context.
        """
        sig = self._env_guard.get_signature()
        
        return AuthenticData(
            data=data,
            source=source,
            timestamp=datetime.utcnow(),
            producer_id=producer,
            environment=sig.mode.value
        )

# Singleton
_auth_guard: Optional[DataAuthenticityGuard] = None

def get_auth_guard(env_guard_instance=None) -> DataAuthenticityGuard:
    global _auth_guard
    if _auth_guard is None:
        if env_guard_instance is None:
             # In a real app this dependency injection would be cleaner
             from .environment_guard import get_environment_guard
             env_guard_instance = get_environment_guard()
        _auth_guard = DataAuthenticityGuard(env_guard_instance)
    return _auth_guard
